name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

permissions:
  pull-requests: read
  contents: read

jobs:
  validate-conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@eacf72885be6976f31d90d3390724caa597ea75a # v4.1.0
        with:
          fetch-depth: 0

      - name: Validate commits
        uses: amannn/action-semantic-pull-request@48620bc4dfe66cb71cc2c06e499465c933156706 # v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommitFormat: false
          validateSingleCommit: false
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
            build
            revert
          scopes: |
            api
            app
            infrastructure
            domain
            db
            auth
            release
          requireScope: false
          disallowScopes: |
            WIP
            BREAKING

  validate-no-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eacf72885be6976f31d90d3390724caa597ea75a # v4.1.0
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Detection
        uses: trufflesecurity/trufflehog@8dafb2c4b570e4a1fd65b718fae6a9f97fa41fcc # v3.76.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
          nosecrets: false
